name: qt_idf CI
on: 
  push:
    branches: 
      - master

jobs:
  build_job:
    name: build job
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: run cmd
      run: env.bat && config.bat && make
      shell: cmd